source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ActionButton_Example', :exclusive => true do
  pod "ActionButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "ActionButton", :path => "../"

  
end
